const lessons = [
    {
      id: 1,
      subject: "Web Mobile Development",
      location: "Kent",
      price: 100,
      spaces: 5,
      image: 'img_1.png',
    },
    {
      id: 2,
      subject: "Enterprise Networking",
      location: "Gillingham",
      price: 600,
      spaces: 5,
      image: 'img_2.png',
    },
    {
      id: 3,
      subject: "Interaction Design",
      location: "Rainham",
      price: 450,
      spaces: 5,
      image: 'img_3.png',
    },
    {
      id: 4,
      subject: "User Experience",
      location: "Woolwich",
      price: 850,
      spaces: 5,
      image: 'img_4.png',
    },
    {
      id: 5,
      subject: "UG Individual Project",
      location: "Kilburn",
      price: 550,
      spaces: 5,
      image: 'img_5.png',

    },
    {
      id: 6,
      subject: "Computer Science",
      location: "Kingsbury",
      price: 150,
      spaces: 5,
      image: 'img_6.png',
    },
    {
      id: 7,
      subject: "Arts and Science",
      location: "Wilesden Green",
      price: 600,
      spaces: 5,
      image: 'img_7.png',
    },
    {
      id: 8,
      subject: "Airport Design",
      location: "Burnt Oak",
      price: 400,
      spaces: 5,
      image: 'img_8.png',
    },
    {
      id: 9,
      subject: "Computer Programs",
      location: "Harrow",
      price: 500,
      spaces: 5,
      image: 'img_9.png',
    },
    {
      id: 10,
      subject: "Neural Networking",
      location: "Wembley",
      price: 150,
      spaces: 5,
      image: 'img_10.png',
    },
  ]

  export default lessons
  